services:
  - docker
language: generic

matrix:
  include:
  - env: PROJECT=ikweb-hs/
    language: nix
    cache:
      directories:
        - $HOME/nix.store
    before_install:
      - nix-env -iA cachix -f https://cachix.org/api/v1/install
      - cachix use mathsermone
      # - sudo mkdir -p /etc/nix
      # - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
      # - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
    # before_cache:
      # - mkdir -p $HOME/nix.store
      # - nix copy --to file://$HOME/nix.store $(nix-build ikweb-hs/nix/default.nix --no-out-link) 
  - env: PROJECT=ikweb/
    node_js: lts
    cache:
      directories:
        - node_modules
  - env: PROJECT=ikapi/
    cache:
      directories:
        - $HOME/.stack
    before_install:
      # Download and unpack the stack executable
      - mkdir -p ~/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - travis_retry curl -sSL https://get.haskellstack.org/ | sh

before_script: 
  - echo $TRAVIS_COMMIT_RANGE
  - chmod +x .travis/project-has-new-commits.sh
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make test-ci && make release; else echo "NO CHANGES SINCE LAST COMMIT"; fi
