services:
  - docker
language: generic

matrix:
  include:
  - env: PROJECT=ikweb/
    node_js: lts
    cache:
      directories:
        - node_modules

before_install: chmod +x .travis/project-has-new-commits.sh
before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make test-$TRAVIS_BRANCH; else echo "NO CHANGES SINCE LAST COMMIT"; fi

deploy:
  provider: script
  script: make release
  on:
    branch: 
      - master
      - develop
