services:
  - docker
language: generic

matrix:
  include:
  - env: PROJECT=ikweb/
    node_js: lts
    cache:
      directories:
        - node_modules
  - env: PROJECT=ikapi/
    cache:
      directories:
        - $HOME/.stack
    before_install:
      # Download and unpack the stack executable
      - mkdir -p ~/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - travis_retry curl -sSL https://get.haskellstack.org/ | sh

before_script: 
  - echo $TRAVIS_COMMIT_RANGE
  - chmod +x .travis/project-has-new-commits.sh
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make test-ci && cd ..; else echo "NO CHANGES SINCE LAST COMMIT"; fi

before_deploy: chmod +x .travis/project-has-new-commits.sh
deploy:
  provider: script
  script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make release && cd ..; else echo "NO CHANGES SINCE LAST COMMIT"; fi
  on:
    branch: 
      - master
      - develop
