services:
  - docker
language: generic

matrix:
  include:
  - env: PROJECT=ikweb-hs/
    language: nix
    cache:
      directories:
        - $HOME/nix.store
    before_install:
      - sudo mkdir -p /etc/nix
      - echo "substituters = https://cache.nixos.org/ https://mathsermone.cachix.org file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
      - echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mathsermone.cachix.org-1:SaHx1ryZ6I2o4E8/QBK/Ty4fbddPNrGcY8SwDcyoAPY=" | sudo tee -a /etc/nix/nix.conf > /dev/null
      - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
    before_cache:
      - mkdir -p $HOME/nix.store
      - cd $HOME/ikweb-hs/common nix copy --to file://$HOME/nix.store -f default.nix --show-trace
      - cd $HOME/ikweb-hs/server nix copy --to file://$HOME/nix.store -f default.nix --show-trace
  - env: PROJECT=ikweb/
    node_js: lts
    cache:
      directories:
        - node_modules
  - env: PROJECT=ikapi/
    cache:
      directories:
        - $HOME/.stack
    before_install:
      # Download and unpack the stack executable
      - mkdir -p ~/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - travis_retry curl -sSL https://get.haskellstack.org/ | sh

before_script: 
  - echo $TRAVIS_COMMIT_RANGE
  - chmod +x .travis/project-has-new-commits.sh
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make test-ci && make build-server; else echo "NO CHANGES SINCE LAST COMMIT"; fi
