services:
  - docker
language: generic

matrix:
  include:
  - env: PROJECT=ikweb/
    node_js: lts
    cache:
      directories:
        - node_modules
  - env: PROJECT=ikapi/
    cache:
      directories:
        - $HOME/.stack
    before_install:
      # Download and unpack the stack executable
      - mkdir -p ~/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tr.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_install: chmod +x .travis/project-has-new-commits.sh
before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && make test-ci; else echo "NO CHANGES SINCE LAST COMMIT"; fi

deploy:
  provider: script
  script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then make release; else echo "NO CHANGES SINCE LAST COMMIT"; fi
  on:
    branch: 
      - master
      - develop
